login:
  path: /login
  controller: App\Controller\LoginController::login
logout:
  path: /logout
  controller: App\Controller\LoginController::logout

homepage:
  path: /
  controller: App\Controller\HomepageController::homepage

quiz_enter:
  path: /quiz/enter
  controller: App\Controller\QuizController::enter
quiz_start:
  path: /quiz/start
  controller: App\Controller\QuizController::start
quiz_answer:
  path: /quiz/answer
  controller: App\Controller\QuizController::answer
