login:
  path: /login
  controller: App\Controller\LoginController::login
logout:
  path: /logout
  controller: App\Controller\LoginController::logout

homepage:
  path: /
  controller: App\Controller\HomepageController::homepage

quiz_enter:
  path: /quiz/enter
  controller: App\Controller\QuizController::enter
quiz_start:
  path: /quiz/start
  controller: App\Controller\QuizController::start
quiz_saved_enter:
  path: /quiz/saved/enter/{quizSavedToken}
  controller: App\Controller\QuizController::enterSaved
quiz_answer:
  path: /quiz/answer
  controller: App\Controller\QuizController::answer
quiz_add_question:
  path: /quiz/addQuizQuestion
  controller: App\Controller\QuizController::addQuizQuestion

profile_main:
  path: /profile
  controller: App\Controller\ProfileController::profile
profile_section:
  path: /profile/section
  controller: App\Controller\ProfileController::section
profile_picture:
  path: /profile/picture
  controller: App\Controller\ProfileController::picture
profile_password:
  path: /profile/password
  controller: App\Controller\ProfileController::password
